
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Sale, UserProfile } from '../types';
import { formatDate, formatCurrency } from '../utils/helpers';

export const generateSalesReport = (
  sales: Sale[], 
  user: UserProfile, 
  title: string,
  dateRange: string
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(22);
  doc.setTextColor(30, 64, 175); // blue-800
  doc.text('IGIHOZO STOCK MANAGEMENT', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setTextColor(55, 65, 81); // gray-700
  doc.text(title, pageWidth / 2, 30, { align: 'center' });

  // Summary Info
  doc.setFontSize(10);
  doc.text(`Generated by: ${user.name} (${user.role})`, 14, 45);
  doc.text(`Date Range: ${dateRange}`, 14, 52);
  doc.text(`Report Date: ${formatDate(new Date())}`, 14, 59);

  // Calculations
  const totalSales = sales.reduce((sum, s) => sum + s.totalPrice, 0);
  const cashTotal = sales.filter(s => s.paymentMethod === 'CASH').reduce((sum, s) => sum + s.totalPrice, 0);
  const momoTotal = sales.filter(s => s.paymentMethod === 'MOMO').reduce((sum, s) => sum + s.totalPrice, 0);

  // Totals Box
  doc.setDrawColor(209, 213, 219);
  doc.rect(14, 65, pageWidth - 28, 25);
  doc.text(`Total Sales: ${formatCurrency(totalSales)}`, 20, 72);
  doc.text(`Cash Payments: ${formatCurrency(cashTotal)}`, 20, 78);
  doc.text(`Mobile Money: ${formatCurrency(momoTotal)}`, 20, 84);

  // Table
  const tableData = sales.map(s => [
    formatDate(s.createdAt),
    s.productName,
    s.quantity.toString(),
    formatCurrency(s.unitPrice),
    formatCurrency(s.totalPrice),
    s.paymentMethod,
    s.sellerName
  ]);

  autoTable(doc, {
    startY: 95,
    head: [['Date', 'Product', 'Qty', 'Unit Price', 'Total', 'Payment', 'Seller']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] }, // blue-600
  });

  // Footer
  const finalY = (doc as any).lastAutoTable?.finalY || 100;
  doc.setFontSize(8);
  doc.text('Thank you for choosing IGIHOZO Systems.', pageWidth / 2, finalY + 20, { align: 'center' });

  doc.save(`IGIHOZO_Report_${new Date().getTime()}.pdf`);
};
